# Generated by Django 5.0.1 on 2024-01-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_sys', '0002_remove_order_status_alter_order_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, help_text='已出單'),
        ),
    ]
